version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  backend:
    container_name: nestjs_api_prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "3001:3001" 
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  frontend:
    container_name: react_ui_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data_prod: